/* DO NOT EDIT THIS FILE - it is machine generated */
		#include <jni.h>
	/* Header for class org_dykman_j_JInterface */

#ifndef _Included_org_dykman_j_JInterface
#define _Included_org_dykman_j_JInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef org_dykman_j_JInterface_MTYOFM
#define org_dykman_j_JInterface_MTYOFM 1L
#undef org_dykman_j_JInterface_MTYOER
#define org_dykman_j_JInterface_MTYOER 2L
#undef org_dykman_j_JInterface_MTYOLOG
#define org_dykman_j_JInterface_MTYOLOG 3L
#undef org_dykman_j_JInterface_MTYOSYS
#define org_dykman_j_JInterface_MTYOSYS 4L
#undef org_dykman_j_JInterface_MTYOEXIT
#define org_dykman_j_JInterface_MTYOEXIT 5L
#undef org_dykman_j_JInterface_MTYOFILE
#define org_dykman_j_JInterface_MTYOFILE 6L
/*
 * Class:     org_dykman_j_JInterface
 * Method:    getVariableNative
 * Signature: (JLjava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_dykman_j_JInterface_getVariableNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    setVariableNative
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_dykman_j_JInterface_setVariableNative
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    callJNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_dykman_j_JInterface_callJNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    destroyJNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dykman_j_JInterface_destroyJNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    initializeJNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_dykman_j_JInterface_initializeJNative
  (JNIEnv *, jobject);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    setEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_dykman_j_JInterface_setEnv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnido
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_dykman_j_JInterface_jnido
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidoz
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_org_dykman_j_JInterface_jnidoz
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidos
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[S
 */
JNIEXPORT jshortArray JNICALL Java_org_dykman_j_JInterface_jnidoi
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidoi
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[I
 */
JNIEXPORT jintArray JNICALL Java_org_dykman_j_JInterface_jnidoi
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidol
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_dykman_j_JInterface_jnidol
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidof
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_dykman_j_JInterface_jnidof
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidod
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_dykman_j_JInterface_jnidod
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidoc
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_dykman_j_JInterface_jnidoc
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidow
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[C
 */
JNIEXPORT jcharArray JNICALL Java_org_dykman_j_JInterface_jnidow
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

/*
 * Class:     org_dykman_j_JInterface
 * Method:    jnidox
 * Signature: (JLjava/lang/Object;Ljava/lang/String;[Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_dykman_j_JInterface_jnidox
  (JNIEnv *, jobject, jlong, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
